### ISSUE TITLE
As a Guild Member I would like to create my own profile pages, so that others might know who I am.

### ISSUE THREAD

**Issue by mtromp** [PillarTechnology/ovrachievers-guild#4]
Acceptance Criteria:

- A members area exists with a landing page that contains the alphabetized list of Guild Members, which will become hyper-links when the member creates a page and adds the link.

- Instructions on how a member would add his/her page to the site.

**Comment by mholtman** [comment]
I'm going to give this a try. I think it is just a matter of making a template.
